// Тексты конструктора. Цифры в них не живут — все числа приходят из lib/rack.
export const KON_COPY = {
  ru: {
    eyebrow: 'Онлайн-конструктор',
    title: 'Спроектируйте склад за три шага',
    lead: 'Тип → размеры → результат. Паллетомест, план, 3D-модель, спецификация и цена — до звонка менеджеру.',
    steps: ['Что храните', 'Помещение или секция', 'Результат'],
    next: 'Дальше', back: 'Назад', recalc: 'Пересчитать',
    types: [
      { key: 'pallet', t: 'Паллеты', d: 'Погрузчик, ричтрак или штабелёр. Паллетный (Mega) стеллаж.' },
      { key: 'medium', t: 'Коробки, товар руками', d: 'Склад, производство, подсобка. Среднегрузовой стеллаж.' },
      { key: 'archive', t: 'Папки и архив', d: 'Документы, короба, картотека. Архивный стеллаж.' },
      { key: 'retail', t: 'Витрина магазина', d: 'Торговый зал. Проектируем индивидуально.' },
      { key: 'unknown', t: 'Не знаю', d: 'Инженер подберёт тип по фото помещения и задаче.' },
    ],
    modes: [
      { key: 'room', t: 'По помещению', d: 'Знаю длину, ширину и потолок — разложите стеллажи сами' },
      { key: 'section', t: 'По секции', d: 'Знаю, сколько секций и ярусов нужно' },
    ],
    room: {
      width: 'Длина, м', depth: 'Ширина, м', ceiling: 'Потолок, м',
      columns: 'Колонны внутри', colStepX: 'Шаг колонн по длине, м', colStepY: 'Шаг колонн по ширине, м',
      dock: 'Ворота на ближней стене', truck: 'Техника',
      palletLoad: 'Вес паллеты, кг', palletHeight: 'Высота паллеты с грузом, мм',
      truckHint: 'Задаёт ширину прохода между рядами',
    },
    section: {
      levels: 'Ярусов балок (пол не считается)', beam: 'Длина балки', sections: 'Секций в ряду', rows: 'Рядов',
      size: 'Типоразмер из прайса',
      beams: { 2700: '2700 мм · 3 паллеты', 3300: '3300 мм · 4 паллеты' },
    },
    engineer: {
      t: 'Этот тип считает инженер',
      d: 'Торговые стеллажи и «не знаю» — под каждый зал свой проект. Оставьте заявку с фото помещения: ответим за 5 минут, расчёт — за 24 часа.',
      cta: 'Оставить заявку',
    },
    result: {
      positions: 'паллетомест', sections: 'секций', rows: 'рядов', levels: 'ярусов',
      frame: 'высота рамы', rackArea: 'м² под стеллажами', area: 'м² помещения', fill: 'площади занято',
      price: 'Цена, расчётная', perPosition: 'за паллетоместо', noVat: 'без НДС', withVat: 'с НДС 12 %',
      note: 'Расчётная цена по прайсу. Точная — после бесплатного замера: уточним пол, колонны и нагрузку.',
      spec: 'Спецификация', qty: 'Кол-во', unit: 'ед.',
      plan: 'План расстановки', scene: '3D-модель', sceneHint: 'тянуть — поворот · щипок или колесо — приближение',
      pdf: 'Сохранить PDF', share: 'Сохранить и отправить коллеге', copied: 'Ссылка скопирована',
      call: 'Вызвать замерщика', callHint: 'Заявка уйдёт вместе с этой конфигурацией',
      leadTitle: 'Замерщик у вас — завтра', leadText: 'Проверим размеры, колонны и пол, уточним цену. По Ташкенту — бесплатно.',
      err: 'Не получилось разложить: ',
      byEngineer: 'Цену для этого типоразмера называет инженер после замера.',
      floorNote: 'Нижний ярус — пол, он тоже считается местом.',
      sticky: { cta: 'Получить спецификацию' },
    },
    guide: {
      t: 'Как это работает',
      items: [
        'Выберите, что храните — тип стеллажа подбирается сам.',
        'Введите помещение: раскладка учтёт колонны, ворота и проход под технику.',
        'Или задайте секции и ярусы, если проект уже есть.',
        'Получите паллетомест, план, 3D, спецификацию и цену.',
        'Отправьте ссылку коллеге или вызовите замерщика — заявка уйдёт с конфигурацией.',
      ],
      skip: 'Понятно',
    },
  },
  uz: {
    eyebrow: 'Onlayn konstruktor',
    title: 'Omboringizni uch qadamda loyihalang',
    lead: 'Tur → oʻlchamlar → natija. Pallet oʻrinlari, reja, 3D model, spetsifikatsiya va narx — menejerga qoʻngʻiroqdan oldin.',
    steps: ['Nima saqlaysiz', 'Xona yoki seksiya', 'Natija'],
    next: 'Keyingi', back: 'Orqaga', recalc: 'Qayta hisoblash',
    types: [
      { key: 'pallet', t: 'Palletlar', d: 'Pogruzchik, richtrak yoki shtabelyor. Palletli (Mega) stellaj.' },
      { key: 'medium', t: 'Qutilar, qoʻlda tovar', d: 'Ombor, ishlab chiqarish, xoʻjalik xonasi. Oʻrta yuklamali stellaj.' },
      { key: 'archive', t: 'Papkalar va arxiv', d: 'Hujjatlar, qutilar, kartoteka. Arxiv stellaji.' },
      { key: 'retail', t: 'Doʻkon vitrinasi', d: 'Savdo zali. Alohida loyihalaymiz.' },
      { key: 'unknown', t: 'Bilmayman', d: 'Muhandis xona surati va vazifa boʻyicha turini tanlaydi.' },
    ],
    modes: [
      { key: 'room', t: 'Xona boʻyicha', d: 'Uzunlik, kenglik va shiftni bilaman — stellajlarni oʻzingiz joylang' },
      { key: 'section', t: 'Seksiya boʻyicha', d: 'Nechta seksiya va yarus kerakligini bilaman' },
    ],
    room: {
      width: 'Uzunlik, m', depth: 'Kenglik, m', ceiling: 'Shift, m',
      columns: 'Ichkarida ustunlar bor', colStepX: 'Ustunlar qadami uzunlik boʻyicha, m', colStepY: 'Ustunlar qadami kenglik boʻyicha, m',
      dock: 'Yaqin devorda darvoza', truck: 'Texnika',
      palletLoad: 'Pallet ogʻirligi, kg', palletHeight: 'Yuk bilan pallet balandligi, mm',
      truckHint: 'Qatorlar orasidagi yoʻlak kengligini belgilaydi',
    },
    section: {
      levels: 'Balka yaruslari (pol hisobga olinmaydi)', beam: 'Balka uzunligi', sections: 'Qatorda seksiyalar', rows: 'Qatorlar',
      size: 'Narxnomadagi oʻlcham',
      beams: { 2700: '2700 mm · 3 pallet', 3300: '3300 mm · 4 pallet' },
    },
    engineer: {
      t: 'Bu turni muhandis hisoblaydi',
      d: 'Savdo stellajlari va «bilmayman» — har bir zal uchun alohida loyiha. Xona surati bilan ariza qoldiring: 5 daqiqada javob beramiz, hisob-kitob — 24 soatda.',
      cta: 'Ariza qoldirish',
    },
    result: {
      positions: 'pallet oʻrni', sections: 'seksiya', rows: 'qator', levels: 'yarus',
      frame: 'rama balandligi', rackArea: 'm² stellaj ostida', area: 'm² xona', fill: 'maydon band',
      price: 'Narx, hisobiy', perPosition: 'bir pallet oʻrni', noVat: 'QQSsiz', withVat: 'QQS 12 % bilan',
      note: 'Narxnoma boʻyicha hisobiy narx. Aniq narx — bepul oʻlchovdan soʻng: pol, ustunlar va yuklamani aniqlaymiz.',
      spec: 'Spetsifikatsiya', qty: 'Soni', unit: 'birlik',
      plan: 'Joylashuv rejasi', scene: '3D model', sceneHint: 'tortish — burish · chimdish yoki gʻildirak — yaqinlashtirish',
      pdf: 'PDF saqlash', share: 'Saqlash va hamkasbga yuborish', copied: 'Havola nusxalandi',
      call: 'Oʻlchovchini chaqirish', callHint: 'Ariza shu konfiguratsiya bilan yuboriladi',
      leadTitle: 'Oʻlchovchi sizda — ertaga', leadText: 'Oʻlchamlar, ustunlar va polni tekshiramiz, narxni aniqlaymiz. Toshkent boʻylab — bepul.',
      err: 'Joylashtirib boʻlmadi: ',
      byEngineer: 'Bu oʻlcham narxini muhandis oʻlchovdan keyin aytadi.',
      floorNote: 'Pastki yarus — pol, u ham oʻrin hisoblanadi.',
      sticky: { cta: 'Spetsifikatsiya olish' },
    },
    guide: {
      t: 'Bu qanday ishlaydi',
      items: [
        'Nima saqlashingizni tanlang — stellaj turi oʻzi tanlanadi.',
        'Xonani kiriting: joylashuv ustunlar, darvoza va texnika yoʻlagini hisobga oladi.',
        'Yoki loyiha bor boʻlsa, seksiya va yaruslarni bering.',
        'Pallet oʻrinlari, reja, 3D, spetsifikatsiya va narxni oling.',
        'Havolani hamkasbga yuboring yoki oʻlchovchini chaqiring — ariza konfiguratsiya bilan ketadi.',
      ],
      skip: 'Tushunarli',
    },
  },
};

export const TRUCK_LABELS = {
  ru: { reachtruck: 'Ричтрак', stacker: 'Штабелёр', counterbal: 'Вилочный погрузчик' },
  uz: { reachtruck: 'Richtrak', stacker: 'Shtabelyor', counterbal: 'Vilkali yuklagich' },
};
