// Тексты раздела «Портфолио» (ТЗ 24.09, этап 4). Сами кейсы — lib/cases.js.
export const PORTFOLIO_T = {
  ru: {
    home: "Главная",
    title: "Портфолио",
    h1: "Реализованные проекты RAXPRO",
    lead: "Склады, магазины, производства и маркетплейсы, где уже стоят наши стеллажи. Цифры — со слов клиентов и по факту монтажа.",
    all: "Все",
    seg: { warehouse: "Склады", shop: "Магазины", marketplace: "Маркетплейсы", production: "Производства" },
    open: "Подробнее о проекте",
    task: "Задача",
    solution: "Решение",
    photos: "Фото объекта",
    others: "Другие проекты",
    formTitle: "Хотите так же?",
    formText: "Оставьте телефон — менеджер перезвонит в рабочее время и назначит бесплатный замер.",
    seoTitle: "Портфолио RAXPRO — реализованные проекты стеллажей в Ташкенте",
    seoDesc: "Кейсы RAXPRO: паллетные, полочные и торговые стеллажи для складов, магазинов и заводов — задача, решение и цифры по каждому объекту.",
    caseSeo: (c) => `${c.title} — ${c.client} | Портфолио RAXPRO`,
  },
  uz: {
    home: "Bosh sahifa",
    title: "Portfolio",
    h1: "RAXPRO amalga oshirgan loyihalar",
    lead: "Stellajlarimiz allaqachon turgan omborlar, doʻkonlar, ishlab chiqarish korxonalari va marketpleyslar. Raqamlar — mijozlar soʻzi va montaj natijasi boʻyicha.",
    all: "Barchasi",
    seg: { warehouse: "Omborlar", shop: "Doʻkonlar", marketplace: "Marketpleyslar", production: "Ishlab chiqarish" },
    open: "Loyiha haqida batafsil",
    task: "Vazifa",
    solution: "Yechim",
    photos: "Obyekt suratlari",
    others: "Boshqa loyihalar",
    formTitle: "Sizga ham shunday kerakmi?",
    formText: "Telefon raqamingizni qoldiring — menejer ish vaqtida qoʻngʻiroq qiladi va bepul oʻlchovni belgilaydi.",
    seoTitle: "RAXPRO portfoliosi — Toshkentda amalga oshirilgan stellaj loyihalari",
    seoDesc: "RAXPRO keyslari: omborlar, doʻkonlar va zavodlar uchun palletli, polkali va savdo stellajlari — har bir obyekt boʻyicha vazifa, yechim va raqamlar.",
    caseSeo: (c) => `${c.title} — ${c.client} | RAXPRO portfoliosi`,
  },
};
