// Тексты главной v2. RU — источник, UZ — по смыслу, siz-форма, oʻ/gʻ.
// Цифры только из research/telegram-digest.md и lib/rack/company.ts.

export const V2 = {
  ru: {
    nav: [
      { label: "Продукция", href: "#produkciya" },
      { label: "3D-расчёт", href: "#3d" },
      { label: "Объекты", href: "#obekty" },
      { label: "Как работаем", href: "#process" },
      { label: "Контакты", href: "#kontakty" },
    ],
    cta: "Получить расчёт",
    call: "Позвонить",
    hero: {
      kicker: "Стеллажи для склада, магазина и архива · Ташкент и вся страна",
      title: ["В тот же склад —", "до 10× больше товара."],
      text: "Считаем расстановку под ваш пол, потолок и технику, привозим со своего склада и монтируем. По Ташкенту — за 24 часа, бесплатно.",
      primary: "Собрать склад в 3D",
      secondary: "Получить расчёт за 24 часа",
      facts: [
        { n: "10", u: "лет", l: "гарантии по документу" },
        { n: "1000", u: "+", l: "сданных объектов" },
        { n: "24", u: "ч", l: "монтаж по Ташкенту" },
        { n: "3,5", u: "т", l: "на ярус" },
      ],
    },
    clients: "Нам доверяют склады, заводы и маркетплейсы",
    products: {
      kicker: "Продукция",
      title: "Шесть систем хранения. Под любую нагрузку — от 80 кг до 3,5 тонн на ярус.",
      text: "Все стеллажи на складе в Ташкенте: стандартные секции отгружаем на следующий день, проектные — считаем за 24 часа.",
      from: "от",
      sum: "сум",
      perLevel: "на ярус",
      project: "цена по проекту",
      more: "Подробнее",
      names: {
        "pallet-frontal": { name: "Паллетные фронтальные", who: "Склады с погрузчиком, дистрибуция, производство" },
        "pallet-driveIn": { name: "Набивные drive-in", who: "Однотипный товар большими партиями, холодильники" },
        "medium-duty": { name: "Среднегрузовые полочные", who: "Склады маркетплейсов, ручная комплектация" },
        archive: { name: "Архивные", who: "Офисы, архивы, аптеки" },
        retail: { name: "Торговые", who: "Магазины у дома, супермаркеты" },
        mezzanine: { name: "Мезонины", who: "Второй этаж хранения без стройки" },
      },
    },
    builder: {
      kicker: "3D-расчёт",
      title: "Введите размеры склада — увидите, сколько в него встанет.",
      text: "Тот же расчётный модуль, которым мы готовим коммерческие предложения: ряды, секции, ярусы и паллето-места считаются с зазорами до стен, проходами под вашу технику и запасом под потолок.",
      width: "Длина помещения, м",
      depth: "Ширина помещения, м",
      ceiling: "Высота до потолка, м",
      pallet: "Высота паллеты с грузом, м",
      load: "Вес паллеты, кг",
      truck: "Техника",
      trucks: { stacker: "Штабелёр", reachtruck: "Ричтрак", counterbal: "Вилочный погрузчик" },
      rows: "рядов",
      sections: "секций",
      levels: "ярусов",
      positions: "паллето-мест",
      frame: "рама",
      aisle: "проход",
      fill: "площади под хранением",
      hint: "Тянуть — поворот · колесо — приближение",
      cta: "Получить КП по этой раскладке",
      loading: "Строим модель…",
      error: "Не сходится: ",
      form: {
        title: "Пришлём расчёт с этой раскладкой",
        name: "Ваше имя",
        phone: "Телефон *",
        submit: "Отправить",
        sending: "Отправляем…",
        ok: "Заявка принята. Менеджер перезвонит и уточнит детали объекта.",
        err: "Не отправилось. Позвоните:",
      },
    },
    objects: {
      kicker: "Объекты",
      title: "Реальные склады, реальные цифры.",
      text: "Не стоковые фото: каждый кадр — объект, который мы замеряли, привозили и монтировали.",
      items: [
        { t: "Caffelito Coffee", d: "Склад кофейни: стеллажи 4 м, 1,5 т на ярус. Поставили и смонтировали за 12 часов.", n: "12", u: "часов", tag: "HoReCa", img: "/works/new3.jpg" },
        { t: "Bloom Shop", d: "Склад косметики для маркетплейса: 30 секций среднегрузовых стеллажей, 2,5 м, 5 полок по 400 кг.", n: "30", u: "секций", tag: "Маркетплейс", img: "/works/new2.jpg" },
        { t: "Super Pack", d: "Паллетные стеллажи для крупнейшего в Узбекистане производителя бумаги и упаковки.", n: "1 т", u: "на ярус", tag: "Завод", img: "/works/w1.jpg" },
        { t: "JAC Motors", d: "Склад автозавода: паллетные стеллажи под интенсивную работу погрузчиков.", n: "4 м", u: "высота", tag: "Автозавод", img: "/works/new1.jpg" },
        { t: "Sayqal Restaurant", d: "Складское помещение ресторана: компактная проектная расстановка.", n: "24", u: "часа", tag: "Ресторан", img: "/works/new4.jpg" },
        { t: "Discovery Invest", d: "Складской комплекс: замер, проект, поставка и монтаж полным циклом.", n: "100 %", u: "под ключ", tag: "Склад", img: "/works/new5.jpg" },
      ],
      all: "Все отзывы в Telegram",
    },
    fears: {
      kicker: "Что обычно беспокоит",
      title: "Четыре страха перед заказом стеллажей — и что мы делаем с каждым.",
      items: [
        { q: "«Привезут не вовремя, монтаж затянут»", a: "Стеллажи лежат на нашем складе в Ташкенте. Стандартные секции отгружаем на следующий день, монтаж по городу — в течение 24 часов. Срок стоит в договоре." },
        { q: "«Прогнётся под грузом»", a: "Металл первого сорта, оцинковка и порошковая окраска. Паспортная нагрузка на ярус — до 3,5 тонн, и мы считаем её под ваш реальный груз, а не «примерно»." },
        { q: "«Гарантия только на словах»", a: "10 лет гарантии — документом, а не обещанием менеджера. На рынке Узбекистана так делаем только мы." },
        { q: "«Нужна вся сумма сразу»", a: "Для частных клиентов и малого бизнеса — рассрочка Uzum Nasiya до 25 млн сум. Для проектов — 50 % предоплата, 50 % после монтажа." },
      ],
    },
    process: {
      kicker: "Как работаем",
      title: "От замера до сданного склада — одной командой.",
      steps: [
        { t: "Замер", d: "Выезжаем на объект бесплатно: помещение, проёмы, колонны, реальные нагрузки." },
        { t: "Проект и расчёт", d: "Раскладка с паллето-местами и КП с точной суммой — за 24 часа." },
        { t: "Поставка", d: "Со своего склада или с завода-партнёра. Сталь, оцинковка, порошковая окраска." },
        { t: "Монтаж", d: "Свои бригады, анкеровка к полу, инструктаж по допустимым нагрузкам." },
      ],
      productionKicker: "Из чего сделано",
      certs: "Сертификаты завода-партнёра",
    },
    founder: {
      role: "Основатель и директор RAX PRO",
    },
    reviews: { kicker: "Отзывы", title: "Что говорят после монтажа", all: "Канал с отзывами" },
    contact: {
      kicker: "Заявка",
      title: "Расскажите про склад — вернёмся с расчётом за 24 часа.",
      text: "Или напишите в Telegram — ответим в рабочее время в течение 5 минут.",
      address: "Адрес",
      hours: "График",
      phones: "Телефоны",
      map: "Открыть в картах",
    },
    faq: { kicker: "Вопросы", title: "Частые вопросы" },
  },
  uz: {
    nav: [
      { label: "Mahsulotlar", href: "#produkciya" },
      { label: "3D hisob", href: "#3d" },
      { label: "Obyektlar", href: "#obekty" },
      { label: "Ish tartibi", href: "#process" },
      { label: "Aloqa", href: "#kontakty" },
    ],
    cta: "Hisob-kitob olish",
    call: "Qoʻngʻiroq",
    hero: {
      kicker: "Ombor, doʻkon va arxiv uchun stellajlar · Toshkent va butun respublika",
      title: ["Oʻsha omborga —", "10 barobargacha koʻp tovar."],
      text: "Polingiz, shipingiz va texnikangizga moslab joylashuvni hisoblaymiz, oʻz omborimizdan yetkazamiz va oʻrnatamiz. Toshkent boʻylab — 24 soatda, bepul.",
      primary: "Omborni 3D da yigʻish",
      secondary: "24 soatda hisob-kitob olish",
      facts: [
        { n: "10", u: "yil", l: "hujjat asosida kafolat" },
        { n: "1000", u: "+", l: "topshirilgan obyekt" },
        { n: "24", u: "soat", l: "Toshkentda montaj" },
        { n: "3,5", u: "t", l: "har yarusga" },
      ],
    },
    clients: "Bizga omborlar, zavodlar va marketpleyslar ishonadi",
    products: {
      kicker: "Mahsulotlar",
      title: "Oltita saqlash tizimi. Har qanday yuk uchun — yarusiga 80 kg dan 3,5 tonnagacha.",
      text: "Barcha stellajlar Toshkentdagi omborimizda: standart seksiyalarni ertasi kuni joʻnatamiz, loyihaviylarini 24 soatda hisoblaymiz.",
      from: "dan",
      sum: "soʻm",
      perLevel: "har yarusga",
      project: "narx loyiha boʻyicha",
      more: "Batafsil",
      names: {
        "pallet-frontal": { name: "Frontal paletli", who: "Pogruzchikli omborlar, distributsiya, ishlab chiqarish" },
        "pallet-driveIn": { name: "Zich drive-in", who: "Bir xil tovar katta partiyalarda, sovutkichlar" },
        "medium-duty": { name: "Oʻrta yuklamali polkali", who: "Marketpleys omborlari, qoʻlda terish" },
        archive: { name: "Arxiv", who: "Ofislar, arxivlar, dorixonalar" },
        retail: { name: "Savdo", who: "Uy yonidagi doʻkonlar, supermarketlar" },
        mezzanine: { name: "Mezoninlar", who: "Qurilishsiz ikkinchi qavat saqlash" },
      },
    },
    builder: {
      kicker: "3D hisob",
      title: "Ombor oʻlchamlarini kiriting — unga qancha sigʻishini koʻrasiz.",
      text: "Tijorat takliflarini tayyorlaydigan oʻsha hisoblash moduli: qatorlar, seksiyalar, yaruslar va palet oʻrinlari devorgacha boʻshliq, texnikangiz uchun oʻtish yoʻli va shipgacha zaxira bilan hisoblanadi.",
      width: "Xona uzunligi, m",
      depth: "Xona kengligi, m",
      ceiling: "Shipgacha balandlik, m",
      pallet: "Yukli palet balandligi, m",
      load: "Palet ogʻirligi, kg",
      truck: "Texnika",
      trucks: { stacker: "Shtabelyor", reachtruck: "Richtrak", counterbal: "Vilkali yuklagich" },
      rows: "qator",
      sections: "seksiya",
      levels: "yarus",
      positions: "palet oʻrni",
      frame: "rama",
      aisle: "oʻtish yoʻli",
      fill: "maydon saqlash ostida",
      hint: "Tortish — burish · gʻildirak — yaqinlashtirish",
      cta: "Shu joylashuv boʻyicha KP olish",
      loading: "Model qurilmoqda…",
      error: "Mos kelmadi: ",
      form: {
        title: "Shu joylashuv bilan hisob-kitob yuboramiz",
        name: "Ismingiz",
        phone: "Telefon *",
        submit: "Yuborish",
        sending: "Yuborilmoqda…",
        ok: "Ariza qabul qilindi. Menejer qoʻngʻiroq qilib, obyekt tafsilotlarini aniqlashtiradi.",
        err: "Yuborilmadi. Qoʻngʻiroq qiling:",
      },
    },
    objects: {
      kicker: "Obyektlar",
      title: "Haqiqiy omborlar, haqiqiy raqamlar.",
      text: "Stok suratlar emas: har bir kadr — biz oʻlchagan, yetkazgan va oʻrnatgan obyekt.",
      items: [
        { t: "Caffelito Coffee", d: "Qahvaxona ombori: 4 m stellajlar, yarusiga 1,5 t. 12 soatda yetkazib oʻrnatdik.", n: "12", u: "soat", tag: "HoReCa", img: "/works/new3.jpg" },
        { t: "Bloom Shop", d: "Marketpleys uchun kosmetika ombori: 30 seksiya oʻrta yuklamali stellaj, 2,5 m, 400 kg lik 5 polka.", n: "30", u: "seksiya", tag: "Marketpleys", img: "/works/new2.jpg" },
        { t: "Super Pack", d: "Oʻzbekistondagi eng yirik qogʻoz va qadoq ishlab chiqaruvchisi uchun paletli stellajlar.", n: "1 t", u: "har yarusga", tag: "Zavod", img: "/works/w1.jpg" },
        { t: "JAC Motors", d: "Avtozavod ombori: pogruzchiklarning jadal ishiga moʻljallangan paletli stellajlar.", n: "4 m", u: "balandlik", tag: "Avtozavod", img: "/works/new1.jpg" },
        { t: "Sayqal Restaurant", d: "Restoran ombor xonasi: ixcham loyihaviy joylashuv.", n: "24", u: "soat", tag: "Restoran", img: "/works/new4.jpg" },
        { t: "Discovery Invest", d: "Ombor majmuasi: oʻlchov, loyiha, yetkazib berish va montaj — toʻliq sikl.", n: "100 %", u: "kalit topshirish", tag: "Ombor", img: "/works/new5.jpg" },
      ],
      all: "Telegramdagi barcha sharhlar",
    },
    fears: {
      kicker: "Odatda nima tashvishlantiradi",
      title: "Stellaj buyurtma qilishdan oldingi toʻrt xavotir — va har biriga javobimiz.",
      items: [
        { q: "«Vaqtida keltirishmaydi, montaj choʻziladi»", a: "Stellajlar Toshkentdagi omborimizda turibdi. Standart seksiyalarni ertasi kuni joʻnatamiz, shahar boʻylab montaj — 24 soat ichida. Muddat shartnomada yoziladi." },
        { q: "«Yuk ostida egilib qoladi»", a: "Birinchi nav metall, sinklash va kukunli boʻyoq. Yarusga pasport yuklamasi — 3,5 tonnagacha, uni «taxminan» emas, sizning haqiqiy yukingizga qarab hisoblaymiz." },
        { q: "«Kafolat faqat ogʻzaki»", a: "10 yil kafolat — menejerning vaʼdasi emas, hujjat bilan. Oʻzbekiston bozorida buni faqat biz qilamiz." },
        { q: "«Butun summa birdaniga kerak»", a: "Xususiy mijozlar va kichik biznes uchun — Uzum Nasiya orqali 25 mln soʻmgacha boʻlib toʻlash. Loyihalar uchun — 50 % oldindan, 50 % montajdan keyin." },
      ],
    },
    process: {
      kicker: "Ish tartibi",
      title: "Oʻlchovdan topshirilgan omborgacha — bitta jamoa.",
      steps: [
        { t: "Oʻlchov", d: "Obyektga bepul chiqamiz: xona, oʻtish joylari, ustunlar, haqiqiy yuklamalar." },
        { t: "Loyiha va hisob", d: "Palet oʻrinlari bilan joylashuv va aniq summali KP — 24 soatda." },
        { t: "Yetkazib berish", d: "Oʻz omborimizdan yoki hamkor zavoddan. Poʻlat, sinklash, kukunli boʻyoq." },
        { t: "Montaj", d: "Oʻz brigadalarimiz, polga ankerlash, ruxsat etilgan yuk boʻyicha yoʻriqnoma." },
      ],
      productionKicker: "Nimadan yasalgan",
      certs: "Hamkor zavod sertifikatlari",
    },
    founder: { role: "RAX PRO asoschisi va direktori" },
    reviews: { kicker: "Sharhlar", title: "Montajdan keyin nima deyishadi", all: "Sharhlar kanali" },
    contact: {
      kicker: "Ariza",
      title: "Ombor haqida aytib bering — 24 soatda hisob-kitob bilan qaytamiz.",
      text: "Yoki Telegramga yozing — ish vaqtida 5 daqiqa ichida javob beramiz.",
      address: "Manzil",
      hours: "Ish vaqti",
      phones: "Telefonlar",
      map: "Xaritada ochish",
    },
    faq: { kicker: "Savollar", title: "Koʻp beriladigan savollar" },
  },
};

export const PRODUCT_LINKS = {
  "pallet-frontal": "/napravleniya/palletnye-stellazhi",
  "pallet-driveIn": "/napravleniya/nabivnye-stellazhi",
  "medium-duty": "/napravleniya/srednegruzovye-stellazhi",
  archive: "/napravleniya/arhivnye-stellazhi",
  retail: "/napravleniya/torgovye-stellazhi",
  mezzanine: null,
};

/** Цена «от» для карточки: минимальная из прайса, иначе нижняя граница вилки. */
export function priceFrom(product) {
  const listed = product.sizes.map((s) => s.price).filter(Boolean);
  if (listed.length) return Math.min(...listed);
  if (product.priceRange) return product.priceRange[0];
  return null;
}

export function fmtUzs(n) {
  return new Intl.NumberFormat("ru-RU").format(n).replace(/ /g, " ");
}
